# Generated by Django 3.2.5 on 2022-04-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='guest-user.jpg', null=True, upload_to='post_images'),
        ),
    ]
